---
title: "Day 2"
author: "BHV"
date: "2023-08-22"
output:
  html_document:
    toc: true
    toc_depth: 2

---

#Day 2 



```{r echo = FALSE}
#Loading 
library(tidyverse)



```

# Nonsense 
<details>
<summary> It's hidden </summary>

```{r}

mtcars %>% ggplot(aes(cyl, hp)) + geom_point() + geom_smooth(method = "lm") + theme_bw()

diamonds %>% ggplot(aes(carat, color, color = price)) + geom_point() + facet_wrap(~color, scales = "free_y")

diamonds %>% ggplot(aes(price, cut, color = color)) + geom_point()

```
</details>

## Exercises pt. 1
```{r}
#Original code and output

ggplot(iris, aes(Petal.Length, Petal.Width)) +
geom_point(size = 3)


#Updated code and output

p1 <- ggplot(iris, aes(Petal.Length, Petal.Width, color = Species, shape = Species)) +
geom_point(size = 3) + theme_bw(base_size = 18) + labs(title = "to obtain this plot")

p1
#Now with facets and free axes

p1 + facet_grid( . ~ Species, scales = "free_x") + labs(subtitle = "x-axis varies")


#faceted by continous variable but applied to intervals.
#using the "cut" function

p1 + facet_wrap(~cut(Petal.Width, breaks = c(0.5,1,1.5,2)), scales = "free_y") 



```
### Leaving Iris

```{r}
df <- dplyr::filter(gapminder::gapminder, year == 1992)

df %>% ggplot(aes(gdpPercap,
                  lifeExp,
                  size = pop/1000000, #Changes the number
                  color = continent
                  )
              ) +
  geom_point()+
  theme_bw(base_size = 16) +
  labs(title = "Gapminder for 1992",
       x = "Gross Domestic Product (log scales)",
       y = "Life expectancy at birth (years)",
       color = "Continent", size = "Population\n (millions)") +
  scale_x_log10()


```

## Exercises pt. 2

```{r}

#1 How can you tell if an object is a tibble?
is_tibble(iris)
is.data.frame(iris)

#2 If you have the name of a variable stored in an object e.g. var <- "mpg"
# How can you extract the reference variable from a tibble?

var <- mpg
names(var)
head(var$manufacturer) # use any of the above $names the print

# var[["manufacturer"]] # does the same
# var[[1]]  more of the same

#3 What does tibble::enframe() do? when might you use it?


# It converts a vector to a tibble

short_vector <- c("one", "two", "three", "four")
short_vector
is_vector(short_vector)

small_tibble <- short_vector %>% enframe()
small_tibble
is_tibble(small_tibble)


#Clean-up
rm(var,
   short_vector,
   small_tibble,
   df,
   p1)

```


