---
title: "Day 5"
author: "BHV"
date: "2023-08-25"
output: 
  html_document:
    code_folding: hide
---

#### Get the Data
```{r}
require(tidyverse)

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

#### Load
```

```{r echo = FALSE}
tuesdata <- tidytuesdayR::tt_load('2023-06-20')
tuesdata <- tidytuesdayR::tt_load(2023, week = 25)

ufo_sightings <- tuesdata$`ufo_sightings`
places <- tuesdata$`places`
day_parts_map <- tuesdata$`day_parts_map`

# Or read in the data manually

ufo_sightings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/ufo_sightings.csv')
places <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/places.csv')
day_parts_map <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/day_parts_map.csv')


```
#### Using the clean up available
```{r echo=FALSE}
# All packages used in this script:
library(tidyverse)
library(here)
library(withr)

url <- "https://github.com/jonthegeek/apis/raw/main/data/data_ufo_reports_with_day_part.rds"
ufo_path <- withr::local_tempfile(fileext = ".rds")
download.file(url, ufo_path)

ufo_data_original <- readRDS(ufo_path)

# We need to make the csv small enough that github won't choke. We'll pull out
# some of the joined data back into separate tables.

ufo_sightings <- ufo_data_original |> 
  dplyr::select(
    reported_date_time:city,
    state, 
    country_code,
    shape:has_images,
    day_part
  ) |> 
  # This got normalized after the data was saved, re-normalize.
  dplyr::mutate(
    shape = tolower(shape)
  )

places <- ufo_data_original |>
  dplyr::select(
    city:country_code, 
    latitude:elevation_m
  ) |> 
  dplyr::distinct()

# We'll also provide the map of "day parts" in case anybody wants to do
# something with that.
url2 <- "https://github.com/jonthegeek/apis/raw/main/data/data_day_parts_map.rds"
day_parts_path <- withr::local_tempfile(fileext = ".rds")
download.file(url2, day_parts_path)

day_parts_map <- readRDS(day_parts_path)
# 
# readr::write_csv(
#   ufo_sightings,
#   here::here(
#     "data",
#     "2023",
#     "2023-06-20",
#     "ufo_sightings.csv"
#   )
# )
# 
# readr::write_csv(
#   places,
#   here::here(
#     "data",
#     "2023",
#     "2023-06-20",
#     "places.csv"
#   )
# )
# 
# readr::write_csv(
#   day_parts_map,
#   here::here(
#     "data",
#     "2023",
#     "2023-06-20",
#     "day_parts_map.csv"
#   )
# )


```

### Now what
```{r}
#unlike on the website there this data set says nobody have images.

ufo_sightings %>% 
  ggplot(aes(has_images, fill = has_images)) +
  geom_bar() + 
  theme_bw() +
  labs(title = "Images of the sighting",
       subtitle = "unlike on the website there this data set says nobody have images")
  
# simplifying day times, because who knows what nautical v astronomical v civil dusk/dawn is  
ufo_sightings2 <- ufo_sightings %>% 
  separate(day_part,into = c("remove",
                             "day_part"), 
           sep = " ", 
           fill = "left") %>% 
  select(-remove) %>% 
  mutate(day_part = factor(day_part, 
                              levels= c("dawn", "morning", "afternoon", "dusk", "night"),
                              labels= c("Dawn", "Morning", "Afternoon", "Dusk", "Night"))
  )

#UFO sightings across part of day
 ufo_sightings2 %>% ggplot(aes(day_part, fill = day_part)) +
  geom_bar(show.legend = F) +
  theme_bw(base_size = 16) +
   labs(title = "UFO sightings across part of day",
        y = "Count",
        x = "Part of day")
 
 #Extracting year of the report
 ufo_sightings2<- ufo_sightings2 %>% mutate(year = str_extract(reported_date_time_utc,"^\\d{4}"))
 
 # UFO sightings across the years
 
 ufo_sightings2 %>% ggplot(aes(year)) +
   geom_bar() +
   theme_bw(base_size = 16) +
   theme(axis.text.x = element_text(angle = 90)) +
   scale_x_discrete(guide = guide_axis(n.dodge=3)) +
   labs(title = "UFO sightings across the years",
        subtitle = "All years",
        y = "Count",
        x = "Year")

# UFO sightings across the years
 
 ufo_sightings2 %>% 
   filter(year >1990) %>% 
   ggplot(aes(year)) +
   geom_bar() +
   theme_bw(base_size = 16) +
   theme(axis.text.x = element_text(angle = 90)) +
   scale_x_discrete(guide = guide_axis(n.dodge=3)) +
   labs(title = "UFO sightings across the years",
        subtitle = "since 1990",
        y = "Count",
        x = "Year")
 
 
#Duration of sightings in seconds through out the day
 
ufo_sightings2 %>%  ggplot(aes(day_part, duration_seconds , fill = day_part)) + 
  geom_point(show.legend = F) + 
  geom_boxplot(show.legend = F) +
  scale_y_log10() +
  labs(title = "Duration of sightings in seconds throughout the day",
       y = "Duration in seconds \nlog scale",
       x = "Part of day") + 
  theme_bw(base_size = 16)

ufo_sightings2 %>% filter(country_code == "DK") %>% view()
dk <- ufo_sightings2 %>% filter(country_code == "DK") %>% 
  mutate(muni = case_when(state == "South Denmark" ~ "syddanmark",
                          state == "Capital Region" ~ "hovedstaden",
                          state == "North Denmark" ~ "nordjylland",
                          state == "Zealand" ~ "sjaelland",
                          state == "Central Jutland" ~ "midtjylland"
                          ))


# UFO sightings in by region Denmark
dk %>% group_by(muni) %>% 
  summarize(n = n()) %>% 
plotDK::plotDK(., 
               id = "muni",
               plotlevel = "region",
               value = "n",
               show_missing = T) +
  binned_scale(aesthetics = "fill",
               scale_name = "stepsn", 
               na.value = "#c9cccf",
               palette = function(x) rev(c("#D53E4F",
                                           "#FC8D59",
                                           "#FEE08B",
                                           "#99D594",
                                           "#3288BD")),
               breaks = c(1,2, 4,6, 8),
               limits = c(0,8),
               show.limits = TRUE, 
               guide = "legend",
               name = "Count"
    ) +
  labs(title = "UFO sightings in by region Denmark",)
 
```

